# Generated by Django 4.0 on 2022-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.IntegerField()),
                ('NationalInsuranceId', models.IntegerField(blank=True, null=True)),
                ('is_agreed', models.BooleanField(default=False)),
                ('is_shadow', models.BooleanField(default=True)),
            ],
        ),
    ]
